name: Deploy Ingress Stack
description: Deploy or upgrade Traefik and cert-manager on a k3s control-plane via SSH
runs:
  using: composite
  steps:
    - name: Deploy Traefik + cert-manager on remote host
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        envs: LE_EMAIL
        script: |
          set -e
          export DISPLAY=
          # Ensure nix profile on PATH (contains helm & kubectl)
          source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh || true
          export PATH="$HOME/.nix-profile/bin:$PATH"
          export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
          export LE_EMAIL="${{ inputs.le_email }}"

          # Add/refresh repos and deploy components
          helm repo add traefik  https://traefik.github.io/charts   || true
          helm repo add jetstack https://charts.jetstack.io         || true
          helm repo update

          helm upgrade --install traefik traefik/traefik \
            --namespace kube-system --create-namespace \
            --set service.type=LoadBalancer \
            --set ports.websecure.port=443

          helm upgrade --install cert-manager jetstack/cert-manager \
            --namespace cert-manager --create-namespace \
            --set installCRDs=true

          cat <<EOF | kubectl apply -f -
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: letsencrypt-prod
          spec:
            acme:
              email: $LE_EMAIL
              server: https://acme-v02.api.letsencrypt.org/directory
              privateKeySecretRef:
                name: acme-account-key
              solvers:
              - http01:
                  ingress:
                    class: traefik
          EOF

          echo "Ingress stack deployed"
inputs:
  host:
    description: Remote host
    required: true
  username:
    description: SSH user
    required: true
  password:
    description: SSH password
    required: true
  le_email:
    description: Let's Encrypt email
    required: true 